spring:
  application:
    name: oj-judge
  profiles:
    active: win

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 6088

oj:
  thread:
    core-size: 8
    max-size: 50
    keep-alive-time: 10
    queue-length: 100

# 自定义添加判题的语言
custom-cmd:
  map:
    11:
      - python2
      - python2 -m py_compile PATH/main.py
      - python2 -m py_compile PATH/main.py
    12:
      - node.js
      - judge.js.runCmd=node PATH/main.js
#    12:
#      - python3
#      - python3 -m py_compile PATH/main.py
#      - python3 -m py_compile PATH/main.py

logging:
  file:
    path: /app/logs
    name: judge.log
  config: classpath:logback.xml