spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.44.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  rabbitmq:
    host: 192.168.44.3
    virtual-host: /
    listener:
      direct:
        acknowledge-mode: manual #消息确认机制