spring:
  application:
    name: oj-platform
  profiles:
    active: win
  mail:
    host: smtp.qq.com
    username: cheerful0120@qq.com
    port: 587
    password: 123456 #use your mail server
    properties:
      mail:
        smtp:
          auth: true
#          socketFactoryClass: javax.net.ssl.SSLSocketFactory
#        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
#        debug: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 5088
  servlet:
    context-path: /platform

oj:
  thread:
    core-size: 8
    max-size: 50
    keep-alive-time: 10