spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: cc200155
    url: jdbc:mysql://localhost:3306/oj_ums?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  rabbitmq:
    host: localhost
    virtual-host: /
    listener:
      direct:
        #消息确认机制
        acknowledge-mode: manual