spring:
  application:
    name: oj-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.44.1:8848
    gateway:
      routes:
        - id: platform-route
          uri: lb://oj-platform
          predicates:
            - Path=/api/platform/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: q-route
          uri: lb://oj-question
          predicates:
            - Path=/api/q/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin-route
          uri: lb://oj-admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

server:
  port: 88
